MartaBernach\MusicStore\ArtistBundle\Entity\Artist:
    type: entity
    table: artists
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        photos:
            targetEntity: ArtistPhoto
            mappedBy: artist
        band_member:
            targetEntity: MartaBernach\MusicStore\BandBundle\Entity\BandMember
            mappedBy: artist
    fields:
        stageName:
            type: string
            length: 255
            column: stage_name
            nullable: true
            options:
                default: null
        slug:
            type: string
            length: 255
            gedmo:
                slug:
                    updatable: true
                    unique: true
                    fields:
                        - stageName
                        - firstName
                        - lastName
        firstName:
            type: string
            length: 255
            column: first_name
        lastName:
            type: string
            length: 255
            column: last_name
        biography:
            type: text
            nullable: true
            options:
                default: null
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
