services:
#    marta_bernach_music_store_genres.example:
#        class: MartaBernach\MusicStore\GenresBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    marta_bernach_music_store_genres.admin.genre:
        class: MartaBernach\MusicStore\GenresBundle\Admin\GenreAdmin
        arguments: [~, MartaBernach\MusicStore\GenresBundle\Entity\Genre, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Gatunki Muzyczne, label: Gatunek Muzyczny}
