marta_bernach_music_store_band:
    resource: "@MartaBernachMusicStoreBandBundle/Resources/config/routing.yml"
    prefix:   /

marta_bernach_music_store_artist:
    resource: "@MartaBernachMusicStoreArtistBundle/Resources/config/routing.yml"
    prefix:   /

marta_bernach_music_store_albums:
    resource: "@MartaBernachMusicStoreAlbumsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
