marta_bernach_music_store_genres:
    resource: "@MartaBernachMusicStoreGenresBundle/Resources/config/routing.yml"
    prefix:   /

marta_bernach_music_store_frontend:
    resource: "@MartaBernachMusicStoreFrontendBundle/Resources/config/routing.yml"
    prefix:   /

marta_bernach_music_store_band:
    resource: "@MartaBernachMusicStoreBandBundle/Resources/config/routing.yml"
    prefix:   /

marta_bernach_music_store_artist:
    resource: "@MartaBernachMusicStoreArtistBundle/Resources/config/routing.yml"
    prefix:   /

marta_bernach_music_store_albums:
    resource: "@MartaBernachMusicStoreAlbumsBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
