MartaBernach\MusicStore\BandBundle\Entity\Band:
    type: entity
    table: bands
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        albums:
            targetEntity: MartaBernach\MusicStore\AlbumsBundle\Entity\Album
            mappedBy: band
            cascade: ["all"]
        members:
            targetEntity: BandMember
            mappedBy: band
            cascade: ["all"]
    fields:
        name:
            type: string
            length: 255
        slug:
            type: string
            length: 255
            gedmo:
                slug:
                    updatable: true
                    unique: true
                    fields:
                        - name
        formed:
            type: integer
        originCountry:
            type: string
            length: 255
            column: origin_country
        originCity:
            type: string
            length: 255
            column: origin_city
        biography:
            type: text
            nullable: true
            options:
                default: null
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
